# Generated by Django 5.0.6 on 2024-07-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_portfolio_app', '0002_rename_img_projects_image_remove_projects_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
